services:
  - type: web
    name: cent-monitor
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: BOT_TOKEN
        value: 8575472491:AAGMQ1g34d9tS1TD0rYOw2s2r0WRlunIt8M
      - key: CHAT_ID
        value: "@Cent"
